# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Orchestrate or schedule a set of jobs
# each jobs runs in isolation in its own docker container
jobs:
  save_hello_world_output:
    docker:
      -  image: circleci/node:13.8.0
    steps:
      - run: echo "hello_world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
        at: ~/
      - run: cat ~/output.txt

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - save_hello_world_output
      - print_output_file:
        requires:
          - save_hello_world_output
# bascially we are running the code we defined above
# and print_world job requires print_hello as prerequsite